initial 1.89 ver
AnacondaRecipes/libansicon-feedstock pull request #1
Opened 2023-12-05 16:23 UTC by M-Waszkiewicz-Anaconda

libansicon 1.89
 - [upstream](https://github.com/adoxa/ansicon)
 - windows only
 - dependency for ansicon

2023-12-05 16:31 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: clone/recipe/meta.yaml:0: missing_tests: No tests were found.
ERROR: clone/recipe/meta.yaml:23: incorrect_license: The recipe's `about/license` key is not an SPDX compliant license or license exception, reference https://spdx.org/licenses/
Errors were found

</details>

2023-12-05 16:54 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: clone/recipe/meta.yaml:0: missing_tests: No tests were found.
ERROR: clone/recipe/meta.yaml:26: incorrect_license: The recipe's `about/license` key is not an SPDX compliant license or license exception, reference https://spdx.org/licenses/
Errors were found

</details>

2023-12-05 17:00 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: clone/recipe/meta.yaml:0: missing_tests: No tests were found.
ERROR: clone/recipe/meta.yaml:26: incorrect_license: The recipe's `about/license` key is not an SPDX compliant license or license exception, reference https://spdx.org/licenses/
Errors were found

</details>

2023-12-05 17:21 UTC, JeanChristopheMorinPerso requested changes

2023-12-05 17:21 UTC, JeanChristopheMorinPerso commented on recipe/meta.yaml
> +  license_family: OTHER
```suggestion
  license: Zlib
  license_family: Zlib
```

2023-12-05 17:28 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: clone/recipe/meta.yaml:0: missing_tests: No tests were found.
ERROR: clone/recipe/meta.yaml:27: incorrect_license: The recipe's `about/license` key is not an SPDX compliant license or license exception, reference https://spdx.org/licenses/
Errors were found

</details>

2023-12-05 21:54 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: clone/recipe/meta.yaml:0: missing_tests: No tests were found.
ERROR: clone/recipe/meta.yaml:35: incorrect_license: The recipe's `about/license` key is not an SPDX compliant license or license exception, reference https://spdx.org/licenses/
Errors were found

</details>

2023-12-05 22:05 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: clone/recipe/meta.yaml:0: missing_tests: No tests were found.
ERROR: clone/recipe/meta.yaml:42: invalid_license_family: The recipe has an incorrect `about/license_family` value.{}
Errors were found

</details>

2023-12-05 22:11 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: clone/recipe/meta.yaml:0: missing_tests: No tests were found.
Errors were found

</details>

2023-12-05 22:18 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: clone/recipe/meta.yaml:0: missing_tests: No tests were found.
Errors were found

</details>

2023-12-05 22:28 UTC, JeanChristopheMorinPerso commented on recipe/meta.yaml
> +    - if not exist %PREFIX_LIB%\include\ansicon.h exit 1     # [win]
I don't think `PREFIX_LIB` is set in tests...

2023-12-05 22:37 UTC, JeanChristopheMorinPerso commented on recipe/meta.yaml
> +    - if not exist %PREFIX_LIB%\ANSI64.lib exit 1     # [win]
```suggestion
    - if not exist %LIBRARY_INC%\ansicon.h exit 1     # [win]
    - if not exist %LIBRARY_INC%\ansicon.rc exit 1     # [win]
    - if not exist %LIBRARY_BIN%\ansicon.exe exit 1     # [win]
    - if not exist %LIBRARY_BIN%\ANSI64.dll exit 1     # [win]
    - if not exist %LIBRARY_LIB%\ANSI64.exp exit 1     # [win]
    - if not exist %LIBRARY_LIB%\ANSI64.lib exit 1     # [win]
```

2023-12-06 08:59 UTC, skupr-anaconda approved these changes

2023-12-06 15:58 UTC, JeanChristopheMorinPerso approved these changes
Good job @M-Waszkiewicz-Anaconda! This wasn't an easy one!

2023-12-06 16:03 UTC, skupr-anaconda reviewed
As it's only for windows

2023-12-06 16:03 UTC, skupr-anaconda commented on recipe/meta.yaml
> +    - 0001-fix-the-build-for-VS-2015.patch
```suggestion
  patches:  # [win]
    - 0001-fix-the-build-for-VS-2015.patch  # [win]
```

2023-12-06 16:10 UTC, merged